# LISTE DES COULEURS
[couleurs]
    blanc = "FFFFFF"
    noir = "000000"
    orange = "FF642e"
    jaune = "FFCB00"
    rose = "FAA1F1"
    rougeClair = "EE0F14"
    rougeFonce = "B00721"
    bleuCiel = "66CCFF"
    bleuFonce = "0086C0"
    mauve = "BDa8F9"
    gris = "808080"
    grisClair = "C4C4C4"
    bleuNoir = "225091"
    vert = "9CD326"
    violet = "784BD1"

# LISTE DES PROFESSEURS
[profs]
     [profs.lorena]
        nom = "Loréna"
        couleur = "blanc"
        fond = "bleuCiel"
        diminutif = "Lor"
        couleur_sac = "bleuCiel"

    [profs.adeline]
        nom = "Adeline"
        couleur = "blanc"
        fond = "orange"
        diminutif = "Ad"
        couleur_sac = "Orange"

    [profs.eleonora]
        nom = "Eleonora"
        couleur = "noir"
        fond = "vert"
        diminutif = "Eleo"
        couleur_sac = "Vert"

    [profs.elaura]
        nom = "Élaura"
        couleur = "noir"
        fond = "blanc"
        diminutif = "El"
        couleur_sac = "Blanc"

    [profs.louise]
        nom = "Louise"
        couleur = "blanc"
        fond = "rougeClair"
        diminutif = "Lo"
        couleur_sac = "Rouge"

     [profs.marie-line]
        nom = "Marie-Line"
        couleur = "blanc"
        fond = "mauve"
        diminutif = "ML"
        couleur_sac = "Violet"

    [profs.anne-charlotte]
        nom = "Anne-Charlotte"
        couleur = "blanc"
        fond = "bleuFonce"
        diminutif = "AC"
        couleur_sac = "Bleu Foncé"

    [profs.angelique]
        nom ="Angélique"
        couleur = "blanc"
        fond = "rose"
        diminutif = "An"
        couleur_sac = "Rose"

    [profs.marie-danielle]
        nom = "Marie-Danielle"
        couleur = "blanc"
        fond = "bleuNoir"
        diminutif = "MD"
        couleur_sac = "Noir"

    [profs.almendra]
        nom = "Almendra"
        couleur = "blanc"
        fond = "rougeFonce"
        diminutif = "Al"
        couleur_sac = "Rouge"

    [profs.sirarpik]
        nom = "Sirarpik"
        couleur = "blanc"
        fond = "noir"
        diminutif = "Si"
        couleur_sac = "Gris"

    [profs.valentine]
        nom = "Valentine"
        couleur = "noir"
        fond = "jaune"
        diminutif = "Va"
        couleur_sac = "Jaune"

    [profs.none]
        nom = "None"
        couleur = "rougeFonce"
        fond = "rougeClair"
        diminutif = "Prof Inconnu"
        couleur_sac = ""

    [profs.claire]
        nom = "Claire"
        couleur = "noir"
        fond = "bleuCiel"
        diminutif = "Cl"
        couleur_sac = "Bleu Ciel"

    [profs.jeanne]
        nom = "Jeanne"
        couleur = "blanc"
        fond = "violet"
        diminutif = "Je"
        couleur_sac = "Violet"


[DataBase]
    annee_scolaire = "23-24" # sert à chercher dans les colonnes des cours
    col_verif = "Inscription 23-24 VÉRIFIÉE" # Nom de la colonne vérifiée pour la saison en cours
    col_saison = "Saison 2023-2024" # Nom de la colonne de la saison en cours
    database_file = "export.xlsx" # Ne devrait pas changer a priori, c’est le nom par défaut de l’export d’Assoconnect
    ordre_gala = "Gala 2024 ordre des cours.xlsx" # Tableau à refaire chaque année sur le même
                                                  # modèle en fonction de l’ordre de passage du gala

