<Screen1>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'Sélectionnez un gala :'
        BoxLayout:
            Button:
                text: 'Gala 1'
                on_release: root.switch_to_screen2('Gala 1')
            Button:
                text: 'Gala 2'
                on_release: root.switch_to_screen2('Gala 2')
            Button:
                text: 'Gala 3'
                on_release: root.switch_to_screen2('Gala 3')
